// Generated by scripts/extract_heart_model.py -- do not edit by hand.
// Regenerate after retraining: python scripts/extract_heart_model.py
//
// Intercept, coefficients and StandardScaler parameters read straight out of
// LR_heart.pkl, scaler_heart.pkl and
// columns_heart.pkl. Consumed by lib/heartModel.js.

const heartModel = {
  "version": "logreg-1",
  "generatedFrom": {
    "model": "LR_heart.pkl",
    "scaler": "scaler_heart.pkl",
    "columns": "columns_heart.pkl"
  },
  "intercept": -0.8987266551025906,
  "classes": [
    0,
    1
  ],
  "columns": [
    "Age",
    "RestingBP",
    "Cholesterol",
    "FastingBS",
    "MaxHR",
    "Oldpeak",
    "Sex_M",
    "ChestPainType_ATA",
    "ChestPainType_NAP",
    "ChestPainType_TA",
    "RestingECG_Normal",
    "RestingECG_ST",
    "ExerciseAngina_Y",
    "ST_Slope_Flat",
    "ST_Slope_Up"
  ],
  "coefficients": [
    0.1641477874673874,
    0.004673683396759529,
    0.03692250158824821,
    1.1168600750298339,
    -0.22029153385496053,
    0.4461522012194796,
    1.3302712111862864,
    -1.4271048232689652,
    -1.2395513086946746,
    -0.9022717901773929,
    -0.01504580480496905,
    -0.1541171829804886,
    1.0141473372447156,
    1.0906527470584657,
    -1.1495113963359762
  ],
  "scaler": {
    "columns": [
      "Age",
      "RestingBP",
      "Cholesterol",
      "MaxHR",
      "Oldpeak"
    ],
    "mean": [
      53.510893246187365,
      132.54030501089323,
      244.51633986928104,
      136.80936819172112,
      0.7200435729847494
    ],
    "scale": [
      9.427477516153495,
      17.98013939164916,
      53.28955775875927,
      25.44646307530939,
      0.9896254866189952
    ]
  }
};

export default heartModel;
