"""
Regenerate lib/heart-model.js from the trained scikit-learn artifacts.

The pickles are the single source of truth for the model. Re-run this whenever
LR_heart.pkl / scaler_heart.pkl / columns_heart.pkl change, so the website never
drifts away from the trained model.

    python scripts/extract_heart_model.py --source "C:/path/to/ML Model"

Outputs the exact numbers the browser needs to reproduce
LogisticRegression.predict_proba() in JavaScript.

A JavaScript module (rather than raw JSON) is emitted on purpose: bare JSON
default-imports require an `with { type: "json" }` attribute under Node's ESM
loader, which would stop `scripts/verify_heart_port.mjs` from running against
the real numbers without a bundler in the loop.
"""

import argparse
import json
import os

import joblib


def main():
    default_source = os.path.join(
        os.path.expanduser("~"), "OneDrive", "Desktop", "ML Model"
    )
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        default=default_source,
        help="Folder holding LR_heart.pkl, scaler_heart.pkl and columns_heart.pkl",
    )
    parser.add_argument("--out", default="lib/heart-model.js")
    args = parser.parse_args()

    model = joblib.load(os.path.join(args.source, "LR_heart.pkl"))
    scaler = joblib.load(os.path.join(args.source, "scaler_heart.pkl"))
    columns = list(joblib.load(os.path.join(args.source, "columns_heart.pkl")))

    # Features that pass through the StandardScaler. The remaining columns are
    # either binary (FastingBS) or one-hot dummies, and stay on their raw scale.
    scaled_names = list(getattr(scaler, "feature_names_in_", []))

    payload = {
        "version": "logreg-1",
        "generatedFrom": {
            "model": "LR_heart.pkl",
            "scaler": "scaler_heart.pkl",
            "columns": "columns_heart.pkl",
        },
        "intercept": float(model.intercept_[0]),
        "classes": [int(c) for c in model.classes_],
        "columns": columns,
        "coefficients": [float(c) for c in model.coef_[0]],
        "scaler": {
            "columns": scaled_names,
            "mean": [float(m) for m in scaler.mean_],
            "scale": [float(s) for s in scaler.scale_],
        },
    }

    assert len(payload["coefficients"]) == len(columns), "coef/column length mismatch"
    for name in payload["scaler"]["columns"]:
        assert name in columns, f"scaled column {name} missing from columns_heart.pkl"

    banner = (
        "// Generated by scripts/extract_heart_model.py -- do not edit by hand.\n"
        "// Regenerate after retraining: python scripts/extract_heart_model.py\n"
        "//\n"
        f"// Intercept, coefficients and StandardScaler parameters read straight out of\n"
        f"// {payload['generatedFrom']['model']}, {payload['generatedFrom']['scaler']} and\n"
        f"// {payload['generatedFrom']['columns']}. Consumed by lib/heartModel.js.\n\n"
    )

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(banner)
        fh.write("const heartModel = ")
        json.dump(payload, fh, indent=2)
        fh.write(";\n\nexport default heartModel;\n")

    print(f"wrote {args.out}: {len(columns)} features, {len(scaled_names)} scaled")


if __name__ == "__main__":
    main()
